/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as CalendarRouteImport } from './routes/_calendar'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SettingsRouteImport } from './routes/_settings'
import { Route as AdminAccountsRouteImport } from './routes/_admin.accounts'
import { Route as AdminActivityRouteImport } from './routes/_admin.activity'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AdminAgentRouteImport } from './routes/_admin.agent'
import { Route as AdminAiUsageRouteImport } from './routes/_admin.ai-usage'
import { Route as AdminApiKeysRouteImport } from './routes/_admin.api-keys'
import { Route as AdminAuditLogsRouteImport } from './routes/_admin.audit-logs'
import { Route as AdminBackupsRouteImport } from './routes/_admin.backups'
import { Route as AdminBrandingRouteImport } from './routes/_admin.branding'
import { Route as AdminDomainsRouteImport } from './routes/_admin.domains'
import { Route as AdminGeneralRouteImport } from './routes/_admin.general'
import { Route as AdminLicensesRouteImport } from './routes/_admin.licenses'
import { Route as AdminMailboxesRouteImport } from './routes/_admin.mailboxes'
import { Route as AdminRoutingRouteImport } from './routes/_admin.routing'
import { Route as AdminWebhooksRouteImport } from './routes/_admin.webhooks'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSetupRouteImport } from './routes/_auth.setup'
import { Route as CalendarBookingRouteImport } from './routes/_calendar.booking'
import { Route as CalendarCalendarRouteImport } from './routes/_calendar.calendar'
import { Route as DashboardArchivedRouteImport } from './routes/_dashboard.archived'
import { Route as DashboardComposeRouteImport } from './routes/_dashboard.compose'
import { Route as DashboardDraftsRouteImport } from './routes/_dashboard.drafts'
import { Route as DashboardImportExportRouteImport } from './routes/_dashboard.import-export'
import { Route as DashboardInboxRouteImport } from './routes/_dashboard.inbox'
import { Route as DashboardRulesRouteImport } from './routes/_dashboard.rules'
import { Route as DashboardSentRouteImport } from './routes/_dashboard.sent'
import { Route as DashboardSnoozedRouteImport } from './routes/_dashboard.snoozed'
import { Route as DashboardSpamRouteImport } from './routes/_dashboard.spam'
import { Route as DashboardStarredRouteImport } from './routes/_dashboard.starred'
import { Route as DashboardTrashRouteImport } from './routes/_dashboard.trash'
import { Route as SettingsSettingsRouteImport } from './routes/_settings.settings'
import { Route as BookUserIdRouteImport } from './routes/book.$userId'
import { Route as CUsernameRouteImport } from './routes/c.$username'
import { Route as AdminAccountsIdRouteImport } from './routes/_admin.accounts_.$id'
import { Route as AdminMailboxesIdRouteImport } from './routes/_admin.mailboxes_.$id'
import { Route as DashboardArchivedIndexRouteImport } from './routes/_dashboard.archived.index'
import { Route as DashboardArchivedMessageIdRouteImport } from './routes/_dashboard.archived.$messageId'
import { Route as DashboardDraftsMessageIdRouteImport } from './routes/_dashboard.drafts_.$messageId'
import { Route as DashboardFoldersFolderIdRouteImport } from './routes/_dashboard.folders.$folderId'
import { Route as DashboardInboxIndexRouteImport } from './routes/_dashboard.inbox.index'
import { Route as DashboardInboxMessageIdRouteImport } from './routes/_dashboard.inbox.$messageId'
import { Route as DashboardSentIndexRouteImport } from './routes/_dashboard.sent.index'
import { Route as DashboardSentMessageIdRouteImport } from './routes/_dashboard.sent.$messageId'
import { Route as DashboardSnoozedIndexRouteImport } from './routes/_dashboard.snoozed.index'
import { Route as DashboardSnoozedMessageIdRouteImport } from './routes/_dashboard.snoozed.$messageId'
import { Route as DashboardSpamIndexRouteImport } from './routes/_dashboard.spam.index'
import { Route as DashboardSpamMessageIdRouteImport } from './routes/_dashboard.spam.$messageId'
import { Route as DashboardStarredIndexRouteImport } from './routes/_dashboard.starred.index'
import { Route as DashboardStarredMessageIdRouteImport } from './routes/_dashboard.starred.$messageId'
import { Route as DashboardTrashIndexRouteImport } from './routes/_dashboard.trash.index'
import { Route as DashboardTrashMessageIdRouteImport } from './routes/_dashboard.trash.$messageId'
import { Route as SettingsSettingsIndexRouteImport } from './routes/_settings.settings.index'
import { Route as SettingsSettingsAccountRouteImport } from './routes/_settings.settings.account'
import { Route as SettingsSettingsApiKeysRouteImport } from './routes/_settings.settings.api-keys'
import { Route as SettingsSettingsAppPasswordsRouteImport } from './routes/_settings.settings.app-passwords'
import { Route as SettingsSettingsAutoReplyRouteImport } from './routes/_settings.settings.auto-reply'
import { Route as SettingsSettingsExportRouteImport } from './routes/_settings.settings.export'
import { Route as SettingsSettingsImportRouteImport } from './routes/_settings.settings.import'
import { Route as SettingsSettingsImportExportRouteImport } from './routes/_settings.settings.import-export'
import { Route as SettingsSettingsInboxRouteImport } from './routes/_settings.settings.inbox'
import { Route as SettingsSettingsRulesRouteImport } from './routes/_settings.settings.rules'
import { Route as SettingsSettingsSecurityRouteImport } from './routes/_settings.settings.security'
import { Route as BookUserIdEventIdRouteImport } from './routes/book.$userId_.$eventId'
import { Route as CUsernameSlugRouteImport } from './routes/c.$username_.$slug'
import { Route as AdminAccountsIdIndexRouteImport } from './routes/_admin.accounts_.$id.index'
import { Route as AdminAccountsIdMailboxesRouteImport } from './routes/_admin.accounts_.$id.mailboxes'
import { Route as AdminAccountsIdPasswordRouteImport } from './routes/_admin.accounts_.$id.password'
import { Route as AdminAccountsIdPermissionsRouteImport } from './routes/_admin.accounts_.$id.permissions'
import { Route as DashboardAgentReviewIdRouteImport } from './routes/_dashboard.agent.review.$id'
import { Route as DashboardFoldersFolderIdIndexRouteImport } from './routes/_dashboard.folders.$folderId.index'
import { Route as DashboardFoldersFolderIdMessageIdRouteImport } from './routes/_dashboard.folders.$folderId.$messageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/_calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneralRoute = AdminGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailboxesRoute = AdminMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutingRoute = AdminRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/_auth/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/_auth/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarBookingRoute = CalendarBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => CalendarRoute,
} as any)
const CalendarCalendarRoute = CalendarCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => CalendarRoute,
} as any)
const DashboardArchivedRoute = DashboardArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComposeRoute = DashboardComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDraftsRoute = DashboardDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportExportRoute = DashboardImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesRoute = DashboardRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSentRoute = DashboardSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSnoozedRoute = DashboardSnoozedRouteImport.update({
  id: '/snoozed',
  path: '/snoozed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpamRoute = DashboardSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStarredRoute = DashboardStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const SettingsSettingsRoute = SettingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SettingsRoute,
} as any)
const BookUserIdRoute = BookUserIdRouteImport.update({
  id: '/book/$userId',
  path: '/book/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const CUsernameRoute = CUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIdRoute = AdminAccountsIdRouteImport.update({
  id: '/accounts_/$id',
  path: '/accounts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailboxesIdRoute = AdminMailboxesIdRouteImport.update({
  id: '/mailboxes_/$id',
  path: '/mailboxes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardArchivedIndexRoute = DashboardArchivedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardArchivedRoute,
} as any)
const DashboardArchivedMessageIdRoute =
  DashboardArchivedMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => DashboardArchivedRoute,
  } as any)
const DashboardDraftsMessageIdRoute =
  DashboardDraftsMessageIdRouteImport.update({
    id: '/drafts_/$messageId',
    path: '/drafts/$messageId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFoldersFolderIdRoute =
  DashboardFoldersFolderIdRouteImport.update({
    id: '/folders/$folderId',
    path: '/folders/$folderId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInboxIndexRoute = DashboardInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInboxRoute,
} as any)
const DashboardInboxMessageIdRoute = DashboardInboxMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => DashboardInboxRoute,
} as any)
const DashboardSentIndexRoute = DashboardSentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSentRoute,
} as any)
const DashboardSentMessageIdRoute = DashboardSentMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => DashboardSentRoute,
} as any)
const DashboardSnoozedIndexRoute = DashboardSnoozedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSnoozedRoute,
} as any)
const DashboardSnoozedMessageIdRoute =
  DashboardSnoozedMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => DashboardSnoozedRoute,
  } as any)
const DashboardSpamIndexRoute = DashboardSpamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSpamRoute,
} as any)
const DashboardSpamMessageIdRoute = DashboardSpamMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => DashboardSpamRoute,
} as any)
const DashboardStarredIndexRoute = DashboardStarredIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStarredRoute,
} as any)
const DashboardStarredMessageIdRoute =
  DashboardStarredMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => DashboardStarredRoute,
  } as any)
const DashboardTrashIndexRoute = DashboardTrashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTrashRoute,
} as any)
const DashboardTrashMessageIdRoute = DashboardTrashMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => DashboardTrashRoute,
} as any)
const SettingsSettingsIndexRoute = SettingsSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsAccountRoute = SettingsSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsApiKeysRoute = SettingsSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsAppPasswordsRoute =
  SettingsSettingsAppPasswordsRouteImport.update({
    id: '/app-passwords',
    path: '/app-passwords',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsAutoReplyRoute =
  SettingsSettingsAutoReplyRouteImport.update({
    id: '/auto-reply',
    path: '/auto-reply',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsExportRoute = SettingsSettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsImportRoute = SettingsSettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsImportExportRoute =
  SettingsSettingsImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsInboxRoute = SettingsSettingsInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsRulesRoute = SettingsSettingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const SettingsSettingsSecurityRoute =
  SettingsSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const BookUserIdEventIdRoute = BookUserIdEventIdRouteImport.update({
  id: '/book/$userId_/$eventId',
  path: '/book/$userId/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CUsernameSlugRoute = CUsernameSlugRouteImport.update({
  id: '/c/$username_/$slug',
  path: '/c/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIdIndexRoute = AdminAccountsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAccountsIdRoute,
} as any)
const AdminAccountsIdMailboxesRoute =
  AdminAccountsIdMailboxesRouteImport.update({
    id: '/mailboxes',
    path: '/mailboxes',
    getParentRoute: () => AdminAccountsIdRoute,
  } as any)
const AdminAccountsIdPasswordRoute = AdminAccountsIdPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AdminAccountsIdRoute,
} as any)
const AdminAccountsIdPermissionsRoute =
  AdminAccountsIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AdminAccountsIdRoute,
  } as any)
const DashboardAgentReviewIdRoute = DashboardAgentReviewIdRouteImport.update({
  id: '/agent/review/$id',
  path: '/agent/review/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFoldersFolderIdIndexRoute =
  DashboardFoldersFolderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFoldersFolderIdRoute,
  } as any)
const DashboardFoldersFolderIdMessageIdRoute =
  DashboardFoldersFolderIdMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => DashboardFoldersFolderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AdminAccountsRoute
  '/activity': typeof AdminActivityRoute
  '/admin': typeof AdminAdminRoute
  '/agent': typeof AdminAgentRoute
  '/ai-usage': typeof AdminAiUsageRoute
  '/api-keys': typeof AdminApiKeysRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/backups': typeof AdminBackupsRoute
  '/branding': typeof AdminBrandingRoute
  '/domains': typeof AdminDomainsRoute
  '/general': typeof AdminGeneralRoute
  '/licenses': typeof AdminLicensesRoute
  '/mailboxes': typeof AdminMailboxesRoute
  '/routing': typeof AdminRoutingRoute
  '/webhooks': typeof AdminWebhooksRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/booking': typeof CalendarBookingRoute
  '/calendar': typeof CalendarCalendarRoute
  '/archived': typeof DashboardArchivedRouteWithChildren
  '/compose': typeof DashboardComposeRoute
  '/drafts': typeof DashboardDraftsRoute
  '/import-export': typeof DashboardImportExportRoute
  '/inbox': typeof DashboardInboxRouteWithChildren
  '/rules': typeof DashboardRulesRoute
  '/sent': typeof DashboardSentRouteWithChildren
  '/snoozed': typeof DashboardSnoozedRouteWithChildren
  '/spam': typeof DashboardSpamRouteWithChildren
  '/starred': typeof DashboardStarredRouteWithChildren
  '/trash': typeof DashboardTrashRouteWithChildren
  '/settings': typeof SettingsSettingsRouteWithChildren
  '/book/$userId': typeof BookUserIdRoute
  '/c/$username': typeof CUsernameRoute
  '/accounts/$id': typeof AdminAccountsIdRouteWithChildren
  '/mailboxes/$id': typeof AdminMailboxesIdRoute
  '/archived/$messageId': typeof DashboardArchivedMessageIdRoute
  '/drafts/$messageId': typeof DashboardDraftsMessageIdRoute
  '/folders/$folderId': typeof DashboardFoldersFolderIdRouteWithChildren
  '/inbox/$messageId': typeof DashboardInboxMessageIdRoute
  '/sent/$messageId': typeof DashboardSentMessageIdRoute
  '/snoozed/$messageId': typeof DashboardSnoozedMessageIdRoute
  '/spam/$messageId': typeof DashboardSpamMessageIdRoute
  '/starred/$messageId': typeof DashboardStarredMessageIdRoute
  '/trash/$messageId': typeof DashboardTrashMessageIdRoute
  '/settings/account': typeof SettingsSettingsAccountRoute
  '/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/settings/app-passwords': typeof SettingsSettingsAppPasswordsRoute
  '/settings/auto-reply': typeof SettingsSettingsAutoReplyRoute
  '/settings/export': typeof SettingsSettingsExportRoute
  '/settings/import': typeof SettingsSettingsImportRoute
  '/settings/import-export': typeof SettingsSettingsImportExportRoute
  '/settings/inbox': typeof SettingsSettingsInboxRoute
  '/settings/rules': typeof SettingsSettingsRulesRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/book/$userId/$eventId': typeof BookUserIdEventIdRoute
  '/c/$username/$slug': typeof CUsernameSlugRoute
  '/archived/': typeof DashboardArchivedIndexRoute
  '/inbox/': typeof DashboardInboxIndexRoute
  '/sent/': typeof DashboardSentIndexRoute
  '/snoozed/': typeof DashboardSnoozedIndexRoute
  '/spam/': typeof DashboardSpamIndexRoute
  '/starred/': typeof DashboardStarredIndexRoute
  '/trash/': typeof DashboardTrashIndexRoute
  '/settings/': typeof SettingsSettingsIndexRoute
  '/accounts/$id/mailboxes': typeof AdminAccountsIdMailboxesRoute
  '/accounts/$id/password': typeof AdminAccountsIdPasswordRoute
  '/accounts/$id/permissions': typeof AdminAccountsIdPermissionsRoute
  '/agent/review/$id': typeof DashboardAgentReviewIdRoute
  '/folders/$folderId/$messageId': typeof DashboardFoldersFolderIdMessageIdRoute
  '/accounts/$id/': typeof AdminAccountsIdIndexRoute
  '/folders/$folderId/': typeof DashboardFoldersFolderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AdminAccountsRoute
  '/activity': typeof AdminActivityRoute
  '/admin': typeof AdminAdminRoute
  '/agent': typeof AdminAgentRoute
  '/ai-usage': typeof AdminAiUsageRoute
  '/api-keys': typeof AdminApiKeysRoute
  '/audit-logs': typeof AdminAuditLogsRoute
  '/backups': typeof AdminBackupsRoute
  '/branding': typeof AdminBrandingRoute
  '/domains': typeof AdminDomainsRoute
  '/general': typeof AdminGeneralRoute
  '/licenses': typeof AdminLicensesRoute
  '/mailboxes': typeof AdminMailboxesRoute
  '/routing': typeof AdminRoutingRoute
  '/webhooks': typeof AdminWebhooksRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/setup': typeof AuthSetupRoute
  '/booking': typeof CalendarBookingRoute
  '/calendar': typeof CalendarCalendarRoute
  '/compose': typeof DashboardComposeRoute
  '/drafts': typeof DashboardDraftsRoute
  '/import-export': typeof DashboardImportExportRoute
  '/rules': typeof DashboardRulesRoute
  '/book/$userId': typeof BookUserIdRoute
  '/c/$username': typeof CUsernameRoute
  '/mailboxes/$id': typeof AdminMailboxesIdRoute
  '/archived/$messageId': typeof DashboardArchivedMessageIdRoute
  '/drafts/$messageId': typeof DashboardDraftsMessageIdRoute
  '/inbox/$messageId': typeof DashboardInboxMessageIdRoute
  '/sent/$messageId': typeof DashboardSentMessageIdRoute
  '/snoozed/$messageId': typeof DashboardSnoozedMessageIdRoute
  '/spam/$messageId': typeof DashboardSpamMessageIdRoute
  '/starred/$messageId': typeof DashboardStarredMessageIdRoute
  '/trash/$messageId': typeof DashboardTrashMessageIdRoute
  '/settings/account': typeof SettingsSettingsAccountRoute
  '/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/settings/app-passwords': typeof SettingsSettingsAppPasswordsRoute
  '/settings/auto-reply': typeof SettingsSettingsAutoReplyRoute
  '/settings/export': typeof SettingsSettingsExportRoute
  '/settings/import': typeof SettingsSettingsImportRoute
  '/settings/import-export': typeof SettingsSettingsImportExportRoute
  '/settings/inbox': typeof SettingsSettingsInboxRoute
  '/settings/rules': typeof SettingsSettingsRulesRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/book/$userId/$eventId': typeof BookUserIdEventIdRoute
  '/c/$username/$slug': typeof CUsernameSlugRoute
  '/archived': typeof DashboardArchivedIndexRoute
  '/inbox': typeof DashboardInboxIndexRoute
  '/sent': typeof DashboardSentIndexRoute
  '/snoozed': typeof DashboardSnoozedIndexRoute
  '/spam': typeof DashboardSpamIndexRoute
  '/starred': typeof DashboardStarredIndexRoute
  '/trash': typeof DashboardTrashIndexRoute
  '/settings': typeof SettingsSettingsIndexRoute
  '/accounts/$id/mailboxes': typeof AdminAccountsIdMailboxesRoute
  '/accounts/$id/password': typeof AdminAccountsIdPasswordRoute
  '/accounts/$id/permissions': typeof AdminAccountsIdPermissionsRoute
  '/agent/review/$id': typeof DashboardAgentReviewIdRoute
  '/folders/$folderId/$messageId': typeof DashboardFoldersFolderIdMessageIdRoute
  '/accounts/$id': typeof AdminAccountsIdIndexRoute
  '/folders/$folderId': typeof DashboardFoldersFolderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_calendar': typeof CalendarRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_settings': typeof SettingsRouteWithChildren
  '/_admin/accounts': typeof AdminAccountsRoute
  '/_admin/activity': typeof AdminActivityRoute
  '/_admin/admin': typeof AdminAdminRoute
  '/_admin/agent': typeof AdminAgentRoute
  '/_admin/ai-usage': typeof AdminAiUsageRoute
  '/_admin/api-keys': typeof AdminApiKeysRoute
  '/_admin/audit-logs': typeof AdminAuditLogsRoute
  '/_admin/backups': typeof AdminBackupsRoute
  '/_admin/branding': typeof AdminBrandingRoute
  '/_admin/domains': typeof AdminDomainsRoute
  '/_admin/general': typeof AdminGeneralRoute
  '/_admin/licenses': typeof AdminLicensesRoute
  '/_admin/mailboxes': typeof AdminMailboxesRoute
  '/_admin/routing': typeof AdminRoutingRoute
  '/_admin/webhooks': typeof AdminWebhooksRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_calendar/booking': typeof CalendarBookingRoute
  '/_calendar/calendar': typeof CalendarCalendarRoute
  '/_dashboard/archived': typeof DashboardArchivedRouteWithChildren
  '/_dashboard/compose': typeof DashboardComposeRoute
  '/_dashboard/drafts': typeof DashboardDraftsRoute
  '/_dashboard/import-export': typeof DashboardImportExportRoute
  '/_dashboard/inbox': typeof DashboardInboxRouteWithChildren
  '/_dashboard/rules': typeof DashboardRulesRoute
  '/_dashboard/sent': typeof DashboardSentRouteWithChildren
  '/_dashboard/snoozed': typeof DashboardSnoozedRouteWithChildren
  '/_dashboard/spam': typeof DashboardSpamRouteWithChildren
  '/_dashboard/starred': typeof DashboardStarredRouteWithChildren
  '/_dashboard/trash': typeof DashboardTrashRouteWithChildren
  '/_settings/settings': typeof SettingsSettingsRouteWithChildren
  '/book/$userId': typeof BookUserIdRoute
  '/c/$username': typeof CUsernameRoute
  '/_admin/accounts_/$id': typeof AdminAccountsIdRouteWithChildren
  '/_admin/mailboxes_/$id': typeof AdminMailboxesIdRoute
  '/_dashboard/archived/$messageId': typeof DashboardArchivedMessageIdRoute
  '/_dashboard/drafts_/$messageId': typeof DashboardDraftsMessageIdRoute
  '/_dashboard/folders/$folderId': typeof DashboardFoldersFolderIdRouteWithChildren
  '/_dashboard/inbox/$messageId': typeof DashboardInboxMessageIdRoute
  '/_dashboard/sent/$messageId': typeof DashboardSentMessageIdRoute
  '/_dashboard/snoozed/$messageId': typeof DashboardSnoozedMessageIdRoute
  '/_dashboard/spam/$messageId': typeof DashboardSpamMessageIdRoute
  '/_dashboard/starred/$messageId': typeof DashboardStarredMessageIdRoute
  '/_dashboard/trash/$messageId': typeof DashboardTrashMessageIdRoute
  '/_settings/settings/account': typeof SettingsSettingsAccountRoute
  '/_settings/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/_settings/settings/app-passwords': typeof SettingsSettingsAppPasswordsRoute
  '/_settings/settings/auto-reply': typeof SettingsSettingsAutoReplyRoute
  '/_settings/settings/export': typeof SettingsSettingsExportRoute
  '/_settings/settings/import': typeof SettingsSettingsImportRoute
  '/_settings/settings/import-export': typeof SettingsSettingsImportExportRoute
  '/_settings/settings/inbox': typeof SettingsSettingsInboxRoute
  '/_settings/settings/rules': typeof SettingsSettingsRulesRoute
  '/_settings/settings/security': typeof SettingsSettingsSecurityRoute
  '/book/$userId_/$eventId': typeof BookUserIdEventIdRoute
  '/c/$username_/$slug': typeof CUsernameSlugRoute
  '/_dashboard/archived/': typeof DashboardArchivedIndexRoute
  '/_dashboard/inbox/': typeof DashboardInboxIndexRoute
  '/_dashboard/sent/': typeof DashboardSentIndexRoute
  '/_dashboard/snoozed/': typeof DashboardSnoozedIndexRoute
  '/_dashboard/spam/': typeof DashboardSpamIndexRoute
  '/_dashboard/starred/': typeof DashboardStarredIndexRoute
  '/_dashboard/trash/': typeof DashboardTrashIndexRoute
  '/_settings/settings/': typeof SettingsSettingsIndexRoute
  '/_admin/accounts_/$id/mailboxes': typeof AdminAccountsIdMailboxesRoute
  '/_admin/accounts_/$id/password': typeof AdminAccountsIdPasswordRoute
  '/_admin/accounts_/$id/permissions': typeof AdminAccountsIdPermissionsRoute
  '/_dashboard/agent/review/$id': typeof DashboardAgentReviewIdRoute
  '/_dashboard/folders/$folderId/$messageId': typeof DashboardFoldersFolderIdMessageIdRoute
  '/_admin/accounts_/$id/': typeof AdminAccountsIdIndexRoute
  '/_dashboard/folders/$folderId/': typeof DashboardFoldersFolderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/activity'
    | '/admin'
    | '/agent'
    | '/ai-usage'
    | '/api-keys'
    | '/audit-logs'
    | '/backups'
    | '/branding'
    | '/domains'
    | '/general'
    | '/licenses'
    | '/mailboxes'
    | '/routing'
    | '/webhooks'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/booking'
    | '/calendar'
    | '/archived'
    | '/compose'
    | '/drafts'
    | '/import-export'
    | '/inbox'
    | '/rules'
    | '/sent'
    | '/snoozed'
    | '/spam'
    | '/starred'
    | '/trash'
    | '/settings'
    | '/book/$userId'
    | '/c/$username'
    | '/accounts/$id'
    | '/mailboxes/$id'
    | '/archived/$messageId'
    | '/drafts/$messageId'
    | '/folders/$folderId'
    | '/inbox/$messageId'
    | '/sent/$messageId'
    | '/snoozed/$messageId'
    | '/spam/$messageId'
    | '/starred/$messageId'
    | '/trash/$messageId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/app-passwords'
    | '/settings/auto-reply'
    | '/settings/export'
    | '/settings/import'
    | '/settings/import-export'
    | '/settings/inbox'
    | '/settings/rules'
    | '/settings/security'
    | '/book/$userId/$eventId'
    | '/c/$username/$slug'
    | '/archived/'
    | '/inbox/'
    | '/sent/'
    | '/snoozed/'
    | '/spam/'
    | '/starred/'
    | '/trash/'
    | '/settings/'
    | '/accounts/$id/mailboxes'
    | '/accounts/$id/password'
    | '/accounts/$id/permissions'
    | '/agent/review/$id'
    | '/folders/$folderId/$messageId'
    | '/accounts/$id/'
    | '/folders/$folderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/activity'
    | '/admin'
    | '/agent'
    | '/ai-usage'
    | '/api-keys'
    | '/audit-logs'
    | '/backups'
    | '/branding'
    | '/domains'
    | '/general'
    | '/licenses'
    | '/mailboxes'
    | '/routing'
    | '/webhooks'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/booking'
    | '/calendar'
    | '/compose'
    | '/drafts'
    | '/import-export'
    | '/rules'
    | '/book/$userId'
    | '/c/$username'
    | '/mailboxes/$id'
    | '/archived/$messageId'
    | '/drafts/$messageId'
    | '/inbox/$messageId'
    | '/sent/$messageId'
    | '/snoozed/$messageId'
    | '/spam/$messageId'
    | '/starred/$messageId'
    | '/trash/$messageId'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/app-passwords'
    | '/settings/auto-reply'
    | '/settings/export'
    | '/settings/import'
    | '/settings/import-export'
    | '/settings/inbox'
    | '/settings/rules'
    | '/settings/security'
    | '/book/$userId/$eventId'
    | '/c/$username/$slug'
    | '/archived'
    | '/inbox'
    | '/sent'
    | '/snoozed'
    | '/spam'
    | '/starred'
    | '/trash'
    | '/settings'
    | '/accounts/$id/mailboxes'
    | '/accounts/$id/password'
    | '/accounts/$id/permissions'
    | '/agent/review/$id'
    | '/folders/$folderId/$messageId'
    | '/accounts/$id'
    | '/folders/$folderId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_calendar'
    | '/_dashboard'
    | '/_settings'
    | '/_admin/accounts'
    | '/_admin/activity'
    | '/_admin/admin'
    | '/_admin/agent'
    | '/_admin/ai-usage'
    | '/_admin/api-keys'
    | '/_admin/audit-logs'
    | '/_admin/backups'
    | '/_admin/branding'
    | '/_admin/domains'
    | '/_admin/general'
    | '/_admin/licenses'
    | '/_admin/mailboxes'
    | '/_admin/routing'
    | '/_admin/webhooks'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/setup'
    | '/_calendar/booking'
    | '/_calendar/calendar'
    | '/_dashboard/archived'
    | '/_dashboard/compose'
    | '/_dashboard/drafts'
    | '/_dashboard/import-export'
    | '/_dashboard/inbox'
    | '/_dashboard/rules'
    | '/_dashboard/sent'
    | '/_dashboard/snoozed'
    | '/_dashboard/spam'
    | '/_dashboard/starred'
    | '/_dashboard/trash'
    | '/_settings/settings'
    | '/book/$userId'
    | '/c/$username'
    | '/_admin/accounts_/$id'
    | '/_admin/mailboxes_/$id'
    | '/_dashboard/archived/$messageId'
    | '/_dashboard/drafts_/$messageId'
    | '/_dashboard/folders/$folderId'
    | '/_dashboard/inbox/$messageId'
    | '/_dashboard/sent/$messageId'
    | '/_dashboard/snoozed/$messageId'
    | '/_dashboard/spam/$messageId'
    | '/_dashboard/starred/$messageId'
    | '/_dashboard/trash/$messageId'
    | '/_settings/settings/account'
    | '/_settings/settings/api-keys'
    | '/_settings/settings/app-passwords'
    | '/_settings/settings/auto-reply'
    | '/_settings/settings/export'
    | '/_settings/settings/import'
    | '/_settings/settings/import-export'
    | '/_settings/settings/inbox'
    | '/_settings/settings/rules'
    | '/_settings/settings/security'
    | '/book/$userId_/$eventId'
    | '/c/$username_/$slug'
    | '/_dashboard/archived/'
    | '/_dashboard/inbox/'
    | '/_dashboard/sent/'
    | '/_dashboard/snoozed/'
    | '/_dashboard/spam/'
    | '/_dashboard/starred/'
    | '/_dashboard/trash/'
    | '/_settings/settings/'
    | '/_admin/accounts_/$id/mailboxes'
    | '/_admin/accounts_/$id/password'
    | '/_admin/accounts_/$id/permissions'
    | '/_dashboard/agent/review/$id'
    | '/_dashboard/folders/$folderId/$messageId'
    | '/_admin/accounts_/$id/'
    | '/_dashboard/folders/$folderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarRoute: typeof CalendarRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
  BookUserIdRoute: typeof BookUserIdRoute
  CUsernameRoute: typeof CUsernameRoute
  BookUserIdEventIdRoute: typeof BookUserIdEventIdRoute
  CUsernameSlugRoute: typeof CUsernameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_calendar': {
      id: '/_calendar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/accounts': {
      id: '/_admin/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/activity': {
      id: '/_admin/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/agent': {
      id: '/_admin/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ai-usage': {
      id: '/_admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/api-keys': {
      id: '/_admin/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-logs': {
      id: '/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/backups': {
      id: '/_admin/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/branding': {
      id: '/_admin/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/domains': {
      id: '/_admin/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/general': {
      id: '/_admin/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof AdminGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/licenses': {
      id: '/_admin/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mailboxes': {
      id: '/_admin/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof AdminMailboxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/routing': {
      id: '/_admin/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AdminRoutingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/webhooks': {
      id: '/_admin/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_calendar/booking': {
      id: '/_calendar/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof CalendarBookingRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/_calendar/calendar': {
      id: '/_calendar/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarCalendarRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/_dashboard/archived': {
      id: '/_dashboard/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof DashboardArchivedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/compose': {
      id: '/_dashboard/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof DashboardComposeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/drafts': {
      id: '/_dashboard/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DashboardDraftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/import-export': {
      id: '/_dashboard/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof DashboardImportExportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inbox': {
      id: '/_dashboard/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/rules': {
      id: '/_dashboard/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof DashboardRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sent': {
      id: '/_dashboard/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof DashboardSentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/snoozed': {
      id: '/_dashboard/snoozed'
      path: '/snoozed'
      fullPath: '/snoozed'
      preLoaderRoute: typeof DashboardSnoozedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/spam': {
      id: '/_dashboard/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof DashboardSpamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/starred': {
      id: '/_dashboard/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof DashboardStarredRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/trash': {
      id: '/_dashboard/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_settings/settings': {
      id: '/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsSettingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/book/$userId': {
      id: '/book/$userId'
      path: '/book/$userId'
      fullPath: '/book/$userId'
      preLoaderRoute: typeof BookUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$username': {
      id: '/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof CUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/accounts_/$id': {
      id: '/_admin/accounts_/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AdminAccountsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mailboxes_/$id': {
      id: '/_admin/mailboxes_/$id'
      path: '/mailboxes/$id'
      fullPath: '/mailboxes/$id'
      preLoaderRoute: typeof AdminMailboxesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/archived/': {
      id: '/_dashboard/archived/'
      path: '/'
      fullPath: '/archived/'
      preLoaderRoute: typeof DashboardArchivedIndexRouteImport
      parentRoute: typeof DashboardArchivedRoute
    }
    '/_dashboard/archived/$messageId': {
      id: '/_dashboard/archived/$messageId'
      path: '/$messageId'
      fullPath: '/archived/$messageId'
      preLoaderRoute: typeof DashboardArchivedMessageIdRouteImport
      parentRoute: typeof DashboardArchivedRoute
    }
    '/_dashboard/drafts_/$messageId': {
      id: '/_dashboard/drafts_/$messageId'
      path: '/drafts/$messageId'
      fullPath: '/drafts/$messageId'
      preLoaderRoute: typeof DashboardDraftsMessageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/folders/$folderId': {
      id: '/_dashboard/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof DashboardFoldersFolderIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inbox/': {
      id: '/_dashboard/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof DashboardInboxIndexRouteImport
      parentRoute: typeof DashboardInboxRoute
    }
    '/_dashboard/inbox/$messageId': {
      id: '/_dashboard/inbox/$messageId'
      path: '/$messageId'
      fullPath: '/inbox/$messageId'
      preLoaderRoute: typeof DashboardInboxMessageIdRouteImport
      parentRoute: typeof DashboardInboxRoute
    }
    '/_dashboard/sent/': {
      id: '/_dashboard/sent/'
      path: '/'
      fullPath: '/sent/'
      preLoaderRoute: typeof DashboardSentIndexRouteImport
      parentRoute: typeof DashboardSentRoute
    }
    '/_dashboard/sent/$messageId': {
      id: '/_dashboard/sent/$messageId'
      path: '/$messageId'
      fullPath: '/sent/$messageId'
      preLoaderRoute: typeof DashboardSentMessageIdRouteImport
      parentRoute: typeof DashboardSentRoute
    }
    '/_dashboard/snoozed/': {
      id: '/_dashboard/snoozed/'
      path: '/'
      fullPath: '/snoozed/'
      preLoaderRoute: typeof DashboardSnoozedIndexRouteImport
      parentRoute: typeof DashboardSnoozedRoute
    }
    '/_dashboard/snoozed/$messageId': {
      id: '/_dashboard/snoozed/$messageId'
      path: '/$messageId'
      fullPath: '/snoozed/$messageId'
      preLoaderRoute: typeof DashboardSnoozedMessageIdRouteImport
      parentRoute: typeof DashboardSnoozedRoute
    }
    '/_dashboard/spam/': {
      id: '/_dashboard/spam/'
      path: '/'
      fullPath: '/spam/'
      preLoaderRoute: typeof DashboardSpamIndexRouteImport
      parentRoute: typeof DashboardSpamRoute
    }
    '/_dashboard/spam/$messageId': {
      id: '/_dashboard/spam/$messageId'
      path: '/$messageId'
      fullPath: '/spam/$messageId'
      preLoaderRoute: typeof DashboardSpamMessageIdRouteImport
      parentRoute: typeof DashboardSpamRoute
    }
    '/_dashboard/starred/': {
      id: '/_dashboard/starred/'
      path: '/'
      fullPath: '/starred/'
      preLoaderRoute: typeof DashboardStarredIndexRouteImport
      parentRoute: typeof DashboardStarredRoute
    }
    '/_dashboard/starred/$messageId': {
      id: '/_dashboard/starred/$messageId'
      path: '/$messageId'
      fullPath: '/starred/$messageId'
      preLoaderRoute: typeof DashboardStarredMessageIdRouteImport
      parentRoute: typeof DashboardStarredRoute
    }
    '/_dashboard/trash/': {
      id: '/_dashboard/trash/'
      path: '/'
      fullPath: '/trash/'
      preLoaderRoute: typeof DashboardTrashIndexRouteImport
      parentRoute: typeof DashboardTrashRoute
    }
    '/_dashboard/trash/$messageId': {
      id: '/_dashboard/trash/$messageId'
      path: '/$messageId'
      fullPath: '/trash/$messageId'
      preLoaderRoute: typeof DashboardTrashMessageIdRouteImport
      parentRoute: typeof DashboardTrashRoute
    }
    '/_settings/settings/': {
      id: '/_settings/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsIndexRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/account': {
      id: '/_settings/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsSettingsAccountRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/api-keys': {
      id: '/_settings/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsSettingsApiKeysRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/app-passwords': {
      id: '/_settings/settings/app-passwords'
      path: '/app-passwords'
      fullPath: '/settings/app-passwords'
      preLoaderRoute: typeof SettingsSettingsAppPasswordsRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/auto-reply': {
      id: '/_settings/settings/auto-reply'
      path: '/auto-reply'
      fullPath: '/settings/auto-reply'
      preLoaderRoute: typeof SettingsSettingsAutoReplyRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/export': {
      id: '/_settings/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsSettingsExportRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/import': {
      id: '/_settings/settings/import'
      path: '/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof SettingsSettingsImportRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/import-export': {
      id: '/_settings/settings/import-export'
      path: '/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof SettingsSettingsImportExportRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/inbox': {
      id: '/_settings/settings/inbox'
      path: '/inbox'
      fullPath: '/settings/inbox'
      preLoaderRoute: typeof SettingsSettingsInboxRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/rules': {
      id: '/_settings/settings/rules'
      path: '/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsSettingsRulesRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/security': {
      id: '/_settings/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSettingsSecurityRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/book/$userId_/$eventId': {
      id: '/book/$userId_/$eventId'
      path: '/book/$userId/$eventId'
      fullPath: '/book/$userId/$eventId'
      preLoaderRoute: typeof BookUserIdEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$username_/$slug': {
      id: '/c/$username_/$slug'
      path: '/c/$username/$slug'
      fullPath: '/c/$username/$slug'
      preLoaderRoute: typeof CUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/accounts_/$id/': {
      id: '/_admin/accounts_/$id/'
      path: '/'
      fullPath: '/accounts/$id/'
      preLoaderRoute: typeof AdminAccountsIdIndexRouteImport
      parentRoute: typeof AdminAccountsIdRoute
    }
    '/_admin/accounts_/$id/mailboxes': {
      id: '/_admin/accounts_/$id/mailboxes'
      path: '/mailboxes'
      fullPath: '/accounts/$id/mailboxes'
      preLoaderRoute: typeof AdminAccountsIdMailboxesRouteImport
      parentRoute: typeof AdminAccountsIdRoute
    }
    '/_admin/accounts_/$id/password': {
      id: '/_admin/accounts_/$id/password'
      path: '/password'
      fullPath: '/accounts/$id/password'
      preLoaderRoute: typeof AdminAccountsIdPasswordRouteImport
      parentRoute: typeof AdminAccountsIdRoute
    }
    '/_admin/accounts_/$id/permissions': {
      id: '/_admin/accounts_/$id/permissions'
      path: '/permissions'
      fullPath: '/accounts/$id/permissions'
      preLoaderRoute: typeof AdminAccountsIdPermissionsRouteImport
      parentRoute: typeof AdminAccountsIdRoute
    }
    '/_dashboard/agent/review/$id': {
      id: '/_dashboard/agent/review/$id'
      path: '/agent/review/$id'
      fullPath: '/agent/review/$id'
      preLoaderRoute: typeof DashboardAgentReviewIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/folders/$folderId/': {
      id: '/_dashboard/folders/$folderId/'
      path: '/'
      fullPath: '/folders/$folderId/'
      preLoaderRoute: typeof DashboardFoldersFolderIdIndexRouteImport
      parentRoute: typeof DashboardFoldersFolderIdRoute
    }
    '/_dashboard/folders/$folderId/$messageId': {
      id: '/_dashboard/folders/$folderId/$messageId'
      path: '/$messageId'
      fullPath: '/folders/$folderId/$messageId'
      preLoaderRoute: typeof DashboardFoldersFolderIdMessageIdRouteImport
      parentRoute: typeof DashboardFoldersFolderIdRoute
    }
  }
}

interface AdminAccountsIdRouteChildren {
  AdminAccountsIdMailboxesRoute: typeof AdminAccountsIdMailboxesRoute
  AdminAccountsIdPasswordRoute: typeof AdminAccountsIdPasswordRoute
  AdminAccountsIdPermissionsRoute: typeof AdminAccountsIdPermissionsRoute
  AdminAccountsIdIndexRoute: typeof AdminAccountsIdIndexRoute
}

const AdminAccountsIdRouteChildren: AdminAccountsIdRouteChildren = {
  AdminAccountsIdMailboxesRoute: AdminAccountsIdMailboxesRoute,
  AdminAccountsIdPasswordRoute: AdminAccountsIdPasswordRoute,
  AdminAccountsIdPermissionsRoute: AdminAccountsIdPermissionsRoute,
  AdminAccountsIdIndexRoute: AdminAccountsIdIndexRoute,
}

const AdminAccountsIdRouteWithChildren = AdminAccountsIdRoute._addFileChildren(
  AdminAccountsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdminRoute: typeof AdminAdminRoute
  AdminAgentRoute: typeof AdminAgentRoute
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminGeneralRoute: typeof AdminGeneralRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  AdminMailboxesRoute: typeof AdminMailboxesRoute
  AdminRoutingRoute: typeof AdminRoutingRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminAccountsIdRoute: typeof AdminAccountsIdRouteWithChildren
  AdminMailboxesIdRoute: typeof AdminMailboxesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAdminRoute: AdminAdminRoute,
  AdminAgentRoute: AdminAgentRoute,
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminGeneralRoute: AdminGeneralRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  AdminMailboxesRoute: AdminMailboxesRoute,
  AdminRoutingRoute: AdminRoutingRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminAccountsIdRoute: AdminAccountsIdRouteWithChildren,
  AdminMailboxesIdRoute: AdminMailboxesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CalendarRouteChildren {
  CalendarBookingRoute: typeof CalendarBookingRoute
  CalendarCalendarRoute: typeof CalendarCalendarRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarBookingRoute: CalendarBookingRoute,
  CalendarCalendarRoute: CalendarCalendarRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

interface DashboardArchivedRouteChildren {
  DashboardArchivedMessageIdRoute: typeof DashboardArchivedMessageIdRoute
  DashboardArchivedIndexRoute: typeof DashboardArchivedIndexRoute
}

const DashboardArchivedRouteChildren: DashboardArchivedRouteChildren = {
  DashboardArchivedMessageIdRoute: DashboardArchivedMessageIdRoute,
  DashboardArchivedIndexRoute: DashboardArchivedIndexRoute,
}

const DashboardArchivedRouteWithChildren =
  DashboardArchivedRoute._addFileChildren(DashboardArchivedRouteChildren)

interface DashboardInboxRouteChildren {
  DashboardInboxMessageIdRoute: typeof DashboardInboxMessageIdRoute
  DashboardInboxIndexRoute: typeof DashboardInboxIndexRoute
}

const DashboardInboxRouteChildren: DashboardInboxRouteChildren = {
  DashboardInboxMessageIdRoute: DashboardInboxMessageIdRoute,
  DashboardInboxIndexRoute: DashboardInboxIndexRoute,
}

const DashboardInboxRouteWithChildren = DashboardInboxRoute._addFileChildren(
  DashboardInboxRouteChildren,
)

interface DashboardSentRouteChildren {
  DashboardSentMessageIdRoute: typeof DashboardSentMessageIdRoute
  DashboardSentIndexRoute: typeof DashboardSentIndexRoute
}

const DashboardSentRouteChildren: DashboardSentRouteChildren = {
  DashboardSentMessageIdRoute: DashboardSentMessageIdRoute,
  DashboardSentIndexRoute: DashboardSentIndexRoute,
}

const DashboardSentRouteWithChildren = DashboardSentRoute._addFileChildren(
  DashboardSentRouteChildren,
)

interface DashboardSnoozedRouteChildren {
  DashboardSnoozedMessageIdRoute: typeof DashboardSnoozedMessageIdRoute
  DashboardSnoozedIndexRoute: typeof DashboardSnoozedIndexRoute
}

const DashboardSnoozedRouteChildren: DashboardSnoozedRouteChildren = {
  DashboardSnoozedMessageIdRoute: DashboardSnoozedMessageIdRoute,
  DashboardSnoozedIndexRoute: DashboardSnoozedIndexRoute,
}

const DashboardSnoozedRouteWithChildren =
  DashboardSnoozedRoute._addFileChildren(DashboardSnoozedRouteChildren)

interface DashboardSpamRouteChildren {
  DashboardSpamMessageIdRoute: typeof DashboardSpamMessageIdRoute
  DashboardSpamIndexRoute: typeof DashboardSpamIndexRoute
}

const DashboardSpamRouteChildren: DashboardSpamRouteChildren = {
  DashboardSpamMessageIdRoute: DashboardSpamMessageIdRoute,
  DashboardSpamIndexRoute: DashboardSpamIndexRoute,
}

const DashboardSpamRouteWithChildren = DashboardSpamRoute._addFileChildren(
  DashboardSpamRouteChildren,
)

interface DashboardStarredRouteChildren {
  DashboardStarredMessageIdRoute: typeof DashboardStarredMessageIdRoute
  DashboardStarredIndexRoute: typeof DashboardStarredIndexRoute
}

const DashboardStarredRouteChildren: DashboardStarredRouteChildren = {
  DashboardStarredMessageIdRoute: DashboardStarredMessageIdRoute,
  DashboardStarredIndexRoute: DashboardStarredIndexRoute,
}

const DashboardStarredRouteWithChildren =
  DashboardStarredRoute._addFileChildren(DashboardStarredRouteChildren)

interface DashboardTrashRouteChildren {
  DashboardTrashMessageIdRoute: typeof DashboardTrashMessageIdRoute
  DashboardTrashIndexRoute: typeof DashboardTrashIndexRoute
}

const DashboardTrashRouteChildren: DashboardTrashRouteChildren = {
  DashboardTrashMessageIdRoute: DashboardTrashMessageIdRoute,
  DashboardTrashIndexRoute: DashboardTrashIndexRoute,
}

const DashboardTrashRouteWithChildren = DashboardTrashRoute._addFileChildren(
  DashboardTrashRouteChildren,
)

interface DashboardFoldersFolderIdRouteChildren {
  DashboardFoldersFolderIdMessageIdRoute: typeof DashboardFoldersFolderIdMessageIdRoute
  DashboardFoldersFolderIdIndexRoute: typeof DashboardFoldersFolderIdIndexRoute
}

const DashboardFoldersFolderIdRouteChildren: DashboardFoldersFolderIdRouteChildren =
  {
    DashboardFoldersFolderIdMessageIdRoute:
      DashboardFoldersFolderIdMessageIdRoute,
    DashboardFoldersFolderIdIndexRoute: DashboardFoldersFolderIdIndexRoute,
  }

const DashboardFoldersFolderIdRouteWithChildren =
  DashboardFoldersFolderIdRoute._addFileChildren(
    DashboardFoldersFolderIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardArchivedRoute: typeof DashboardArchivedRouteWithChildren
  DashboardComposeRoute: typeof DashboardComposeRoute
  DashboardDraftsRoute: typeof DashboardDraftsRoute
  DashboardImportExportRoute: typeof DashboardImportExportRoute
  DashboardInboxRoute: typeof DashboardInboxRouteWithChildren
  DashboardRulesRoute: typeof DashboardRulesRoute
  DashboardSentRoute: typeof DashboardSentRouteWithChildren
  DashboardSnoozedRoute: typeof DashboardSnoozedRouteWithChildren
  DashboardSpamRoute: typeof DashboardSpamRouteWithChildren
  DashboardStarredRoute: typeof DashboardStarredRouteWithChildren
  DashboardTrashRoute: typeof DashboardTrashRouteWithChildren
  DashboardDraftsMessageIdRoute: typeof DashboardDraftsMessageIdRoute
  DashboardFoldersFolderIdRoute: typeof DashboardFoldersFolderIdRouteWithChildren
  DashboardAgentReviewIdRoute: typeof DashboardAgentReviewIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardArchivedRoute: DashboardArchivedRouteWithChildren,
  DashboardComposeRoute: DashboardComposeRoute,
  DashboardDraftsRoute: DashboardDraftsRoute,
  DashboardImportExportRoute: DashboardImportExportRoute,
  DashboardInboxRoute: DashboardInboxRouteWithChildren,
  DashboardRulesRoute: DashboardRulesRoute,
  DashboardSentRoute: DashboardSentRouteWithChildren,
  DashboardSnoozedRoute: DashboardSnoozedRouteWithChildren,
  DashboardSpamRoute: DashboardSpamRouteWithChildren,
  DashboardStarredRoute: DashboardStarredRouteWithChildren,
  DashboardTrashRoute: DashboardTrashRouteWithChildren,
  DashboardDraftsMessageIdRoute: DashboardDraftsMessageIdRoute,
  DashboardFoldersFolderIdRoute: DashboardFoldersFolderIdRouteWithChildren,
  DashboardAgentReviewIdRoute: DashboardAgentReviewIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsSettingsRouteChildren {
  SettingsSettingsAccountRoute: typeof SettingsSettingsAccountRoute
  SettingsSettingsApiKeysRoute: typeof SettingsSettingsApiKeysRoute
  SettingsSettingsAppPasswordsRoute: typeof SettingsSettingsAppPasswordsRoute
  SettingsSettingsAutoReplyRoute: typeof SettingsSettingsAutoReplyRoute
  SettingsSettingsExportRoute: typeof SettingsSettingsExportRoute
  SettingsSettingsImportRoute: typeof SettingsSettingsImportRoute
  SettingsSettingsImportExportRoute: typeof SettingsSettingsImportExportRoute
  SettingsSettingsInboxRoute: typeof SettingsSettingsInboxRoute
  SettingsSettingsRulesRoute: typeof SettingsSettingsRulesRoute
  SettingsSettingsSecurityRoute: typeof SettingsSettingsSecurityRoute
  SettingsSettingsIndexRoute: typeof SettingsSettingsIndexRoute
}

const SettingsSettingsRouteChildren: SettingsSettingsRouteChildren = {
  SettingsSettingsAccountRoute: SettingsSettingsAccountRoute,
  SettingsSettingsApiKeysRoute: SettingsSettingsApiKeysRoute,
  SettingsSettingsAppPasswordsRoute: SettingsSettingsAppPasswordsRoute,
  SettingsSettingsAutoReplyRoute: SettingsSettingsAutoReplyRoute,
  SettingsSettingsExportRoute: SettingsSettingsExportRoute,
  SettingsSettingsImportRoute: SettingsSettingsImportRoute,
  SettingsSettingsImportExportRoute: SettingsSettingsImportExportRoute,
  SettingsSettingsInboxRoute: SettingsSettingsInboxRoute,
  SettingsSettingsRulesRoute: SettingsSettingsRulesRoute,
  SettingsSettingsSecurityRoute: SettingsSettingsSecurityRoute,
  SettingsSettingsIndexRoute: SettingsSettingsIndexRoute,
}

const SettingsSettingsRouteWithChildren =
  SettingsSettingsRoute._addFileChildren(SettingsSettingsRouteChildren)

interface SettingsRouteChildren {
  SettingsSettingsRoute: typeof SettingsSettingsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsRoute: SettingsSettingsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarRoute: CalendarRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
  BookUserIdRoute: BookUserIdRoute,
  CUsernameRoute: CUsernameRoute,
  BookUserIdEventIdRoute: BookUserIdEventIdRoute,
  CUsernameSlugRoute: CUsernameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
